version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile.backend
    container_name: homeassistant-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/homeassistant
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db
    networks:
      - homeassistant-net

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: homeassistant-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - homeassistant-net

  db:
    image: postgres:15
    container_name: homeassistant-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=homeassistant
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - homeassistant-net

  jenkins:
    image: jenkins/jenkins:lts
    container_name: homeassistant-jenkins
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - homeassistant-net

volumes:
  postgres_data:
  jenkins_home:

networks:
  homeassistant-net:
