spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/homeassistant
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # lub validate / migrate, zale≈ºnie od Flyway/Liquibase
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
