name: Deploy to Raspberry Pi

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Stop running containers
        run: |
          docker compose down || true

      - name: Pull latest changes
        run: |
          git fetch --all
          git reset --hard origin/main

      - name: Build and start stack
        run: |
          docker compose build --no-cache
          docker compose up -d

      - name: Cleanup old unused Docker data
        run: |
          docker system prune -f
